// ===== MOCK DATA (fallback) — โครงตรงกับ schema garments/customers/occasions =====
window.MOCK = {
  OCCASIONS: {
    wedding_guest:'งานแต่ง', dinner:'ดินเนอร์', party:'งานเลี้ยง',
    work:'ทำงาน', cafe:'คาเฟ่', graduation:'รับปริญญา',
    merit:'งานบุญ', festival:'เทศกาล', trip:'ทริป',
  },
  CUSTOMER: {
    name:'คุณมายา', bust_in: 35, waist_in: 30, hip_in: 38, height_cm: 162,
    shoe_size:'38', my_color_season:'winter', credit_balance: 160,
    notes:'',
  },
  EVENT: {
    title:'งานแต่งเพื่อน', day:'12', month:'ก.ค.',
    occasion:'wedding_guest', dress_code:'ค็อกเทล',
  },
  // สถานที่ dress code + สีที่เหมาะ (mock; production = LLOOP Atelier บน Claude)
  VENUES: [
    { match:['โรงแรม','hotel','บอลรูม','ballroom','รูฟท็อป','rooftop'], venue_type:'โรงแรม/รูฟท็อป โทนหรู', dress_code:'ค็อกเทล', occasion:'party',
      colors:['#15233F','#0E8A5F','#F3C6D3'], photo_tip:'แสงวอร์มของโรงแรมรับโทนเข้ม-อัญมณี ทำให้ผิวดูสว่าง ถ่ายออกมาหรู',
      avoid:'สีสะท้อนแสง/นีออน จะดูแข็งกับแสงในร่ม', note:'โรงแรมหรู เลี่ยงลำลองเกินไป'},
    { match:['งานแต่ง','wedding','พิธี'], venue_type:'งานแต่ง', dress_code:'ค็อกเทล', occasion:'wedding_guest',
      colors:['#F3C6D3','#9FB7AC','#15233F'], photo_tip:'พาสเทล/เซจถ่ายกับดอกไม้และฉากงานแต่งสวยละมุน',
      avoid:'ขาวล้วน (สีเจ้าสาว) และดำล้วนจัด', note:'แขกงานแต่ง ดูสุภาพแต่มีสไตล์'},
    { match:['คาเฟ่','cafe','คาเฟ','ร้านกาแฟ'], venue_type:'คาเฟ่ โทนเอิร์ธ', dress_code:'ลำลอง', occasion:'cafe',
      colors:['#D8C8AE','#7E7A33','#D6A02E'], photo_tip:'โทนเอิร์ธเข้ากับไม้/ปูนของคาเฟ่ ถ่ายฟีดสวยกลมกลืน',
      avoid:'สีฉูดฉาดตัดกับโทนร้านมากเกิน', note:'สบาย ๆ แต่ดูมีรสนิยม'},
    { match:['ทะเล','beach','ริมทะเล','พูลวิลล่า','พูล'], venue_type:'ริมทะเล/พูล แสงจ้า', dress_code:'ลำลอง', occasion:'trip',
      colors:['#F3C6D3','#BFE3EC','#FFFFFF'], photo_tip:'สีสว่าง/พาสเทลรับแดดและน้ำทะเล ถ่ายสดใส',
      avoid:'ผ้าหนาทึบ สีหม่นจะดูจมกับแสงจ้า', note:'ผ้าบางพลิ้ว ใส่สบาย'},
    { match:['ออฟฟิศ','office','ประชุม','สัมมนา'], venue_type:'ออฟฟิศ/ประชุม', dress_code:'สมาร์ทแคชชวล', occasion:'work',
      colors:['#1A1A1A','#15233F','#7E7A33'], photo_tip:'โทนเข้มดูโปรกับแสงไฟออฟฟิศ',
      avoid:'สีหวานจัด/ลายเยอะ', note:'สุภาพ เรียบ ดูน่าเชื่อถือ'},
    { match:['รับปริญญา','graduation'], venue_type:'รับปริญญา', dress_code:'ทางการ', occasion:'graduation',
      colors:['#15233F','#1E47A6','#1A1A1A'], photo_tip:'โทนเข้มถ่ายกับชุดครุยและฉากพิธีดูเรียบร้อย',
      avoid:'สีสว่างจัดแย่งซีนชุดครุย', note:'สุภาพทางการ'},
],
  GARMENTS: [
    { id:'g1', name:'Maple satin slip', brand:'Lookbook', tier:'Standard', price:320,
      fabric:'ซาตินโพลี 95% สแปนเด็กซ์ 5%', fabric_en:'95% poly satin, 5% spandex', stretch:'slight', lining:true, sheer:false, weight:'ทิ้งตัว',
      bust:[32,36], waist:[26,30], hip:null, length:92,
      colors:[['navy','#15233F'],['red','#D5142B'],['emerald','#0E8A5F']],
      season:'winter', occasion_tags:['dinner','party'], bg:'#E7E2DA', isNew:true,
      styling_tips:['ใส่บราเกาะอก/สายใส','ซ่อนสายในได้ดี','แนะนำแผ่นปิดจุก','ทรงเข้ารูป—ชุดกระชับช่วยเก็บสัดส่วน'],
      tips_en:['Wear a strapless or clear-strap bra','Hides straps well','Nipple covers recommended','Body-hugging — shapewear helps'] },
    { id:'g2', name:'Céleste chiffon midi', brand:'Maison', tier:'Premium', price:550,
      fabric:'ชีฟอง 100%', fabric_en:'100% chiffon', stretch:'none', lining:true, sheer:false, weight:'บาง พลิ้ว',
      bust:[33,37], waist:[27,29], hip:null, length:120,
      colors:[['blush','#F3C6D3'],['sage','#9FB7AC']],
      season:'summer', occasion_tags:['wedding_guest','party'], bg:'#EFE4E8', isNew:true,
      styling_tips:['มีซับในแล้ว ไม่ต้องใส่ซ้อน','บราสายใสหรือเกาะอก','รองเท้าส้นสูงให้ขายาว'],
      tips_en:['Already lined — no slip needed','Clear-strap or strapless bra','Heels elongate the legs'] },
    { id:'g3', name:'Field linen set', brand:'Field & Co', tier:'Standard', price:300,
      fabric:'ลินิน 70% คอตตอน 30%', fabric_en:'70% linen, 30% cotton', stretch:'none', lining:false, sheer:false, weight:'กลาง',
      bust:[32,38], waist:[26,34], hip:null, length:null,
      colors:[['sand','#D8C8AE'],['olive','#7E7A33']],
      season:'autumn', occasion_tags:['cafe','work','trip'], bg:'#E3DCC9', isNew:false,
      styling_tips:['ใส่บราปกติได้','เนื้อลินินยับเล็กน้อยเป็นเสน่ห์','สนีกเกอร์/รองเท้าแตะหนัง'],
      tips_en:['A regular bra is fine','Light linen creasing is part of the charm','Sneakers or leather sandals'] },
    { id:'g4', name:'Noir blazer dress', brand:'Noir Atelier', tier:'Premium', price:520,
      fabric:'เครป โพลี 95% สแปนเด็กซ์ 5%', fabric_en:'95% poly crepe, 5% spandex', stretch:'slight', lining:true, sheer:false, weight:'หนา อยู่ทรง',
      bust:[33,36], waist:[27,30], hip:null, length:96,
      colors:[['black','#1A1A1A']],
      season:'winter', occasion_tags:['work','dinner'], bg:'#D8D4CE', isNew:false,
      styling_tips:['ใส่บราปกติ','เข็มขัดเน้นเอวได้','รองเท้าคัตชู/บูทสั้น'],
      tips_en:['A regular bra is fine','Add a belt to define the waist','Pumps or ankle boots'] },
    { id:'g5', name:'Marigold cotton midi', brand:'Marigold', tier:'Value', price:170,
      fabric:'คอตตอน 100%', fabric_en:'100% cotton', stretch:'none', lining:false, sheer:false, weight:'กลาง',
      bust:[34,40], waist:[28,36], hip:null, length:110,
      colors:[['mustard','#D6A02E'],['terracotta','#C77B4E']],
      season:'autumn', occasion_tags:['cafe','festival','merit'], bg:'#E7D6B8', isNew:false,
      styling_tips:['ใส่บราปกติ','ผ้าฝ้ายใส่สบาย ระบายอากาศ','รองเท้าแตะ/สนีกเกอร์'],
      tips_en:['A regular bra is fine','Breathable, comfy cotton','Sandals or sneakers'] },
    { id:'g6', name:'Azure halter gown', brand:'Azur', tier:'Premium', price:580,
      fabric:'ซาตินไหมเทียม', fabric_en:'Faux-silk satin', stretch:'none', lining:true, sheer:false, weight:'หนา ทิ้งตัว',
      bust:[32,35], waist:[25,29], hip:null, length:140,
      colors:[['royal blue','#1E47A6']],
      season:'winter', occasion_tags:['wedding_guest','graduation'], bg:'#CFD8E6', isNew:true,
      styling_tips:['คอฮอลเตอร์—ใส่บราเกาะอกไร้สาย หรือแผ่นยกทรง','ซ่อนสายในไม่ได้ ต้องไร้สาย','แนะนำแผ่นปิดจุก','รองเท้าส้นสูง'],
      tips_en:['Halter neck — strapless bra or stick-on cups','Straps can’t be hidden, go strapless','Nipple covers recommended','Heels'] },
],
};
